### ISSUE TITLE
Strawberry Django Permissions Classes: has_permission not being passed source object

### ISSUE THREAD

**Issue by insomniac34** [strawberry-graphql/strawberry-graphql-django#163] opened 2022-08-04 20:20 UTC
## Describe the Bug

In Django, when implementing a Strawberry permission class such as in the following source code, `has_permission`'s `source` arg is always None. (tagging @patrick91 from the Discord channel)

```Python
import strawberry
from .contact_node import ContactNode
from .contact_order import ContactOrder
from typing import List
from app.permissions import IsAuthenticated


class ContactQueryPermission(strawberry.permission.BasePermission):
    message = "User does not have access to this Contact"

    # `source` is always None here 
    def has_permission(self, source, info, **kwargs) -> bool:
        return True


@strawberry.type
class ContactQuery:
    """
    Query definition for both individual and multiple `Contact` objects
    """

    contacts: List[ContactNode] = strawberry.django.field(
        permission_classes=[IsAuthenticated, ContactQueryPermission],
        pagination=True,
        order=ContactOrder,
    )
```

**Comment by bellini666** [comment] 2022-08-06 22:46
Hi @insomniac34 ,

That's actually correct. The source is `None` because you are resolving a field `contacts` in the root query, which has no parent and thus is `None`

For curiosity, what are you trying to achieve?

**Comment by insomniac34** [comment] 2022-08-08 17:10
@bellini666 I am trying to achieve object-level security here. Basically, for every Contact that is being returned by this query, I want to run some logic verifying that the user has access to this object. It's kind of a "last step" of security to make sure the query is returning allowed data.

**Comment by insomniac34** [comment] 2022-08-08 17:20
I was hoping to get this function called for each object in the result set or once with the resultset being passed in via source for me to check

**Comment by insomniac34** [comment] 2022-08-08 17:23
My question is basically: If not via `source`, how do I gain access to the data being returned in a Permission class so that I can check the user/data relationship?

**Comment by bellini666** [comment] 2022-08-08 17:32
From what I understand (@patrick91 correct me if I'm wrong), the permission checking there is done before actually resolving the field, meaning that you don't have actually access to what is being returned in it.

To do that you would need to use a [custom extension](https://strawberry.rocks/docs/guides/custom-extensions), in which you have access to the values both before and after being resolved.

I also have the same problem in some of my projects and I solved that by implementing [permissioned resolved](https://blb-ventures.github.io/strawberry-django-plus/quickstart/#permissioned-resolvers) in strawberry-django-plus lib. It depends on a custom extension that executes schema directives, and you can use `HasObjPerm` to check if the user has permission to the object being returned. It works for both objects and lists, in which it will basically check permissions for each object in the list and filter out the ones that he doesn't have access (or, if using `django-guardian`, it has an integration in which it will execute a query already filtering by objects that the user has access to).

**Comment by insomniac34** [comment] 2022-08-08 20:40
Ah ok. I think what is confusing me is, in the Django REST Framework, permission classes give you access to the data being returned. So, because the Strawberry permission classes appear to be based on them (from a class layout + naming perspective), this was a behavior I assumed was present from the start. @patrick91 let me know if I am misunderstanding anything - in the meantime I will look at alternative methods of checking object permissions.

**Comment by bellini666** [comment] 2023-07-30 16:21
In v0.10.0 there's a new way to define permissions using field extensions: https://strawberry-graphql.github.io/strawberry-graphql-django/guide/permissions/#permissions

It should allow to handle the issues in this issue, so I'm closing the issue. If the issue is not solved, please tell me so I can reopen it :)

**Closed by bellini666** 2023-07-30 16:21 UTC
Labels: bug
